/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package OpenIGTLink.swig;

public class ByteArr {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ByteArr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ByteArr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IGTLheaderJNI.delete_ByteArr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ByteArr(int nelements) {
    this(IGTLheaderJNI.new_ByteArr(nelements), true);
  }

  public short getitem(int index) {
    return IGTLheaderJNI.ByteArr_getitem(swigCPtr, this, index);
  }

  public void setitem(int index, short value) {
    IGTLheaderJNI.ByteArr_setitem(swigCPtr, this, index, value);
  }

  public SWIGTYPE_p_unsigned_char cast() {
    long cPtr = IGTLheaderJNI.ByteArr_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public static ByteArr frompointer(SWIGTYPE_p_unsigned_char t) {
    long cPtr = IGTLheaderJNI.ByteArr_frompointer(SWIGTYPE_p_unsigned_char.getCPtr(t));
    return (cPtr == 0) ? null : new ByteArr(cPtr, false);
  }

}
