/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package OpenIGTLink.swig;

public class IGTLpointJNI {
  public final static native int IGTL_SIZEOF_CHAR_get();
  public final static native int IGTL_SIZEOF_INT_get();
  public final static native int IGTL_SIZEOF_SHORT_get();
  public final static native int IGTL_SIZEOF_LONG_get();
  public final static native int IGTL_SIZEOF_FLOAT_get();
  public final static native int IGTL_SIZEOF_DOUBLE_get();
  public final static native int IGTL_TYPE_USE_LONG_LONG_get();
  public final static native int IGTL_SIZEOF_LONG_LONG_get();
  public final static native long new_ByteArr(int jarg1);
  public final static native void delete_ByteArr(long jarg1);
  public final static native short ByteArr_getitem(long jarg1, ByteArr jarg1_, int jarg2);
  public final static native void ByteArr_setitem(long jarg1, ByteArr jarg1_, int jarg2, short jarg3);
  public final static native long ByteArr_cast(long jarg1, ByteArr jarg1_);
  public final static native long ByteArr_frompointer(long jarg1);
  public final static native int IGTL_POINT_ELEMENT_SIZE_get();
  public final static native int IGTL_POINT_LEN_NAME_get();
  public final static native int IGTL_POINT_LEN_GROUP_NAME_get();
  public final static native int IGTL_POINT_LEN_OWNER_get();
  public final static native void igtl_point_element_name_set(long jarg1, igtl_point_element jarg1_, String jarg2);
  public final static native String igtl_point_element_name_get(long jarg1, igtl_point_element jarg1_);
  public final static native void igtl_point_element_group_name_set(long jarg1, igtl_point_element jarg1_, String jarg2);
  public final static native String igtl_point_element_group_name_get(long jarg1, igtl_point_element jarg1_);
  public final static native void igtl_point_element_rgba_set(long jarg1, igtl_point_element jarg1_, long jarg2);
  public final static native long igtl_point_element_rgba_get(long jarg1, igtl_point_element jarg1_);
  public final static native void igtl_point_element_position_set(long jarg1, igtl_point_element jarg1_, long jarg2);
  public final static native long igtl_point_element_position_get(long jarg1, igtl_point_element jarg1_);
  public final static native void igtl_point_element_radius_set(long jarg1, igtl_point_element jarg1_, float jarg2);
  public final static native float igtl_point_element_radius_get(long jarg1, igtl_point_element jarg1_);
  public final static native void igtl_point_element_owner_set(long jarg1, igtl_point_element jarg1_, String jarg2);
  public final static native String igtl_point_element_owner_get(long jarg1, igtl_point_element jarg1_);
  public final static native long new_igtl_point_element();
  public final static native void delete_igtl_point_element(long jarg1);
  public final static native void igtl_point_convert_byte_order(long jarg1, igtl_point_element jarg1_, int jarg2);
  public final static native java.math.BigInteger igtl_point_get_crc(long jarg1, igtl_point_element jarg1_, int jarg2);
}
