/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package OpenIGTLink.swig;

public class IGTLstring implements IGTLstringConstants {
  public static long igtl_string_get_string_length(igtl_string_header header) {
    return IGTLstringJNI.igtl_string_get_string_length(igtl_string_header.getCPtr(header), header);
  }

  public static void igtl_string_convert_byte_order(igtl_string_header header) {
    IGTLstringJNI.igtl_string_convert_byte_order(igtl_string_header.getCPtr(header), header);
  }

  public static java.math.BigInteger igtl_string_get_crc(igtl_string_header header, SWIGTYPE_p_void string) {
    return IGTLstringJNI.igtl_string_get_crc(igtl_string_header.getCPtr(header), header, SWIGTYPE_p_void.getCPtr(string));
  }

}
