/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package OpenIGTLink.swig;

public interface IGTLndarrayConstants {
  public final static int IGTL_SIZEOF_CHAR = IGTLndarrayJNI.IGTL_SIZEOF_CHAR_get();
  public final static int IGTL_SIZEOF_INT = IGTLndarrayJNI.IGTL_SIZEOF_INT_get();
  public final static int IGTL_SIZEOF_SHORT = IGTLndarrayJNI.IGTL_SIZEOF_SHORT_get();
  public final static int IGTL_SIZEOF_LONG = IGTLndarrayJNI.IGTL_SIZEOF_LONG_get();
  public final static int IGTL_SIZEOF_FLOAT = IGTLndarrayJNI.IGTL_SIZEOF_FLOAT_get();
  public final static int IGTL_SIZEOF_DOUBLE = IGTLndarrayJNI.IGTL_SIZEOF_DOUBLE_get();
  public final static int IGTL_TYPE_USE_LONG_LONG = IGTLndarrayJNI.IGTL_TYPE_USE_LONG_LONG_get();
  public final static int IGTL_SIZEOF_LONG_LONG = IGTLndarrayJNI.IGTL_SIZEOF_LONG_LONG_get();
  public final static int IGTL_NDARRAY_HEADER_SIZE = IGTLndarrayJNI.IGTL_NDARRAY_HEADER_SIZE_get();
  public final static int IGTL_NDARRAY_STYPE_TYPE_INT8 = IGTLndarrayJNI.IGTL_NDARRAY_STYPE_TYPE_INT8_get();
  public final static int IGTL_NDARRAY_STYPE_TYPE_UINT8 = IGTLndarrayJNI.IGTL_NDARRAY_STYPE_TYPE_UINT8_get();
  public final static int IGTL_NDARRAY_STYPE_TYPE_INT16 = IGTLndarrayJNI.IGTL_NDARRAY_STYPE_TYPE_INT16_get();
  public final static int IGTL_NDARRAY_STYPE_TYPE_UINT16 = IGTLndarrayJNI.IGTL_NDARRAY_STYPE_TYPE_UINT16_get();
  public final static int IGTL_NDARRAY_STYPE_TYPE_INT32 = IGTLndarrayJNI.IGTL_NDARRAY_STYPE_TYPE_INT32_get();
  public final static int IGTL_NDARRAY_STYPE_TYPE_UINT32 = IGTLndarrayJNI.IGTL_NDARRAY_STYPE_TYPE_UINT32_get();
  public final static int IGTL_NDARRAY_STYPE_TYPE_FLOAT32 = IGTLndarrayJNI.IGTL_NDARRAY_STYPE_TYPE_FLOAT32_get();
  public final static int IGTL_NDARRAY_STYPE_TYPE_FLOAT64 = IGTLndarrayJNI.IGTL_NDARRAY_STYPE_TYPE_FLOAT64_get();
  public final static int IGTL_NDARRAY_STYPE_TYPE_COMPLEX = IGTLndarrayJNI.IGTL_NDARRAY_STYPE_TYPE_COMPLEX_get();
  public final static int IGTL_NDARRAY_HOST_TO_NETWORK = IGTLndarrayJNI.IGTL_NDARRAY_HOST_TO_NETWORK_get();
  public final static int IGTL_NDARRAY_NETWORK_TO_HOST = IGTLndarrayJNI.IGTL_NDARRAY_NETWORK_TO_HOST_get();
}
