/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package OpenIGTLink.swig;

public interface IGTLheaderConstants {
  public final static int IGTL_SIZEOF_CHAR = IGTLheaderJNI.IGTL_SIZEOF_CHAR_get();
  public final static int IGTL_SIZEOF_INT = IGTLheaderJNI.IGTL_SIZEOF_INT_get();
  public final static int IGTL_SIZEOF_SHORT = IGTLheaderJNI.IGTL_SIZEOF_SHORT_get();
  public final static int IGTL_SIZEOF_LONG = IGTLheaderJNI.IGTL_SIZEOF_LONG_get();
  public final static int IGTL_SIZEOF_FLOAT = IGTLheaderJNI.IGTL_SIZEOF_FLOAT_get();
  public final static int IGTL_SIZEOF_DOUBLE = IGTLheaderJNI.IGTL_SIZEOF_DOUBLE_get();
  public final static int IGTL_TYPE_USE_LONG_LONG = IGTLheaderJNI.IGTL_TYPE_USE_LONG_LONG_get();
  public final static int IGTL_SIZEOF_LONG_LONG = IGTLheaderJNI.IGTL_SIZEOF_LONG_LONG_get();
  public final static int IGTL_HEADER_VERSION = IGTLheaderJNI.IGTL_HEADER_VERSION_get();
  public final static int IGTL_HEADER_SIZE = IGTLheaderJNI.IGTL_HEADER_SIZE_get();
  public final static int IGTL_HEADER_TYPE_SIZE = IGTLheaderJNI.IGTL_HEADER_TYPE_SIZE_get();
  public final static int IGTL_HEADER_NAME_SIZE = IGTLheaderJNI.IGTL_HEADER_NAME_SIZE_get();
  public final static int IGTL_HEADER_TYPESIZE = IGTLheaderJNI.IGTL_HEADER_TYPESIZE_get();
  public final static int IGTL_HEADER_NAMESIZE = IGTLheaderJNI.IGTL_HEADER_NAMESIZE_get();
  public final static int IGTL_HEADER_DEVSIZE = IGTLheaderJNI.IGTL_HEADER_DEVSIZE_get();
  public final static int IGTL_TYPE_PREFIX_NONE = IGTLheaderJNI.IGTL_TYPE_PREFIX_NONE_get();
  public final static int IGTL_TYPE_PREFIX_GET = IGTLheaderJNI.IGTL_TYPE_PREFIX_GET_get();
  public final static int IGTL_TYPE_PREFIX_STT = IGTLheaderJNI.IGTL_TYPE_PREFIX_STT_get();
  public final static int IGTL_TYPE_PREFIX_STP = IGTLheaderJNI.IGTL_TYPE_PREFIX_STP_get();
  public final static int IGTL_TYPE_PREFIX_RTS = IGTLheaderJNI.IGTL_TYPE_PREFIX_RTS_get();
  public final static int IGTL_NUM_TYPE_PREFIX = IGTLheaderJNI.IGTL_NUM_TYPE_PREFIX_get();
}
