/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package OpenIGTLink.swig;

public class IGTLheaderJNI {
  public final static native int IGTL_SIZEOF_CHAR_get();
  public final static native int IGTL_SIZEOF_INT_get();
  public final static native int IGTL_SIZEOF_SHORT_get();
  public final static native int IGTL_SIZEOF_LONG_get();
  public final static native int IGTL_SIZEOF_FLOAT_get();
  public final static native int IGTL_SIZEOF_DOUBLE_get();
  public final static native int IGTL_TYPE_USE_LONG_LONG_get();
  public final static native int IGTL_SIZEOF_LONG_LONG_get();
  public final static native long new_ByteArr(int jarg1);
  public final static native void delete_ByteArr(long jarg1);
  public final static native short ByteArr_getitem(long jarg1, ByteArr jarg1_, int jarg2);
  public final static native void ByteArr_setitem(long jarg1, ByteArr jarg1_, int jarg2, short jarg3);
  public final static native long ByteArr_cast(long jarg1, ByteArr jarg1_);
  public final static native long ByteArr_frompointer(long jarg1);
  public final static native int IGTL_HEADER_VERSION_get();
  public final static native int IGTL_HEADER_SIZE_get();
  public final static native int IGTL_HEADER_TYPE_SIZE_get();
  public final static native int IGTL_HEADER_NAME_SIZE_get();
  public final static native int IGTL_HEADER_TYPESIZE_get();
  public final static native int IGTL_HEADER_NAMESIZE_get();
  public final static native int IGTL_HEADER_DEVSIZE_get();
  public final static native int IGTL_TYPE_PREFIX_NONE_get();
  public final static native int IGTL_TYPE_PREFIX_GET_get();
  public final static native int IGTL_TYPE_PREFIX_STT_get();
  public final static native int IGTL_TYPE_PREFIX_STP_get();
  public final static native int IGTL_TYPE_PREFIX_RTS_get();
  public final static native int IGTL_NUM_TYPE_PREFIX_get();
  public final static native void igtl_header_version_set(long jarg1, igtl_header jarg1_, int jarg2);
  public final static native int igtl_header_version_get(long jarg1, igtl_header jarg1_);
  public final static native void igtl_header_name_set(long jarg1, igtl_header jarg1_, String jarg2);
  public final static native String igtl_header_name_get(long jarg1, igtl_header jarg1_);
  public final static native void igtl_header_device_name_set(long jarg1, igtl_header jarg1_, String jarg2);
  public final static native String igtl_header_device_name_get(long jarg1, igtl_header jarg1_);
  public final static native void igtl_header_timestamp_set(long jarg1, igtl_header jarg1_, java.math.BigInteger jarg2);
  public final static native java.math.BigInteger igtl_header_timestamp_get(long jarg1, igtl_header jarg1_);
  public final static native void igtl_header_body_size_set(long jarg1, igtl_header jarg1_, java.math.BigInteger jarg2);
  public final static native java.math.BigInteger igtl_header_body_size_get(long jarg1, igtl_header jarg1_);
  public final static native void igtl_header_crc_set(long jarg1, igtl_header jarg1_, java.math.BigInteger jarg2);
  public final static native java.math.BigInteger igtl_header_crc_get(long jarg1, igtl_header jarg1_);
  public final static native long new_igtl_header();
  public final static native void delete_igtl_header(long jarg1);
  public final static native void igtl_header_convert_byte_order(long jarg1, igtl_header jarg1_);
  public final static native long PackHeader(long jarg1, igtl_header jarg1_, long jarg2);
}
