/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package OpenIGTLink.swig;

public class IGTLheader implements IGTLheaderConstants {
  public static void igtl_header_convert_byte_order(igtl_header header) {
    IGTLheaderJNI.igtl_header_convert_byte_order(igtl_header.getCPtr(header), header);
  }

  public static SWIGTYPE_p_unsigned_char PackHeader(igtl_header header, SWIGTYPE_p_unsigned_char body) {
    long cPtr = IGTLheaderJNI.PackHeader(igtl_header.getCPtr(header), header, SWIGTYPE_p_unsigned_char.getCPtr(body));
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

}
