/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package OpenIGTLink.swig;

public interface IGTLstringConstants {
  public final static int IGTL_SIZEOF_CHAR = IGTLstringJNI.IGTL_SIZEOF_CHAR_get();
  public final static int IGTL_SIZEOF_INT = IGTLstringJNI.IGTL_SIZEOF_INT_get();
  public final static int IGTL_SIZEOF_SHORT = IGTLstringJNI.IGTL_SIZEOF_SHORT_get();
  public final static int IGTL_SIZEOF_LONG = IGTLstringJNI.IGTL_SIZEOF_LONG_get();
  public final static int IGTL_SIZEOF_FLOAT = IGTLstringJNI.IGTL_SIZEOF_FLOAT_get();
  public final static int IGTL_SIZEOF_DOUBLE = IGTLstringJNI.IGTL_SIZEOF_DOUBLE_get();
  public final static int IGTL_TYPE_USE_LONG_LONG = IGTLstringJNI.IGTL_TYPE_USE_LONG_LONG_get();
  public final static int IGTL_SIZEOF_LONG_LONG = IGTLstringJNI.IGTL_SIZEOF_LONG_LONG_get();
  public final static int IGTL_STRING_HEADER_SIZE = IGTLstringJNI.IGTL_STRING_HEADER_SIZE_get();
}
