/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package OpenIGTLink.swig;

public class IGTLndarray implements IGTLndarrayConstants {
  public static void igtl_ndarray_init_info(igtl_ndarray_info info) {
    IGTLndarrayJNI.igtl_ndarray_init_info(igtl_ndarray_info.getCPtr(info), info);
  }

  public static int igtl_ndarray_alloc_info(igtl_ndarray_info info, SWIGTYPE_p_unsigned_short size) {
    return IGTLndarrayJNI.igtl_ndarray_alloc_info(igtl_ndarray_info.getCPtr(info), info, SWIGTYPE_p_unsigned_short.getCPtr(size));
  }

  public static int igtl_ndarray_free_info(igtl_ndarray_info info) {
    return IGTLndarrayJNI.igtl_ndarray_free_info(igtl_ndarray_info.getCPtr(info), info);
  }

  public static int igtl_ndarray_unpack(int type, SWIGTYPE_p_void byte_array, igtl_ndarray_info info, java.math.BigInteger pack_size) {
    return IGTLndarrayJNI.igtl_ndarray_unpack(type, SWIGTYPE_p_void.getCPtr(byte_array), igtl_ndarray_info.getCPtr(info), info, pack_size);
  }

  public static int igtl_ndarray_pack(igtl_ndarray_info info, SWIGTYPE_p_void byte_array, int type) {
    return IGTLndarrayJNI.igtl_ndarray_pack(igtl_ndarray_info.getCPtr(info), info, SWIGTYPE_p_void.getCPtr(byte_array), type);
  }

  public static java.math.BigInteger igtl_ndarray_get_size(igtl_ndarray_info info, int type) {
    return IGTLndarrayJNI.igtl_ndarray_get_size(igtl_ndarray_info.getCPtr(info), info, type);
  }

  public static java.math.BigInteger igtl_ndarray_get_crc(igtl_ndarray_info info, int type, SWIGTYPE_p_void byte_array) {
    return IGTLndarrayJNI.igtl_ndarray_get_crc(igtl_ndarray_info.getCPtr(info), info, type, SWIGTYPE_p_void.getCPtr(byte_array));
  }

}
