/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package OpenIGTLink.swig;

public class igtl_string_header {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected igtl_string_header(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(igtl_string_header obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IGTLstringJNI.delete_igtl_string_header(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEncoding(int value) {
    IGTLstringJNI.igtl_string_header_encoding_set(swigCPtr, this, value);
  }

  public int getEncoding() {
    return IGTLstringJNI.igtl_string_header_encoding_get(swigCPtr, this);
  }

  public void setLength(int value) {
    IGTLstringJNI.igtl_string_header_length_set(swigCPtr, this, value);
  }

  public int getLength() {
    return IGTLstringJNI.igtl_string_header_length_get(swigCPtr, this);
  }

  public igtl_string_header() {
    this(IGTLstringJNI.new_igtl_string_header(), true);
  }

}
