/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package OpenIGTLink.swig;

public interface IGTLutilConstants {
  public final static int IGTL_SIZEOF_CHAR = IGTLutilJNI.IGTL_SIZEOF_CHAR_get();
  public final static int IGTL_SIZEOF_INT = IGTLutilJNI.IGTL_SIZEOF_INT_get();
  public final static int IGTL_SIZEOF_SHORT = IGTLutilJNI.IGTL_SIZEOF_SHORT_get();
  public final static int IGTL_SIZEOF_LONG = IGTLutilJNI.IGTL_SIZEOF_LONG_get();
  public final static int IGTL_SIZEOF_FLOAT = IGTLutilJNI.IGTL_SIZEOF_FLOAT_get();
  public final static int IGTL_SIZEOF_DOUBLE = IGTLutilJNI.IGTL_SIZEOF_DOUBLE_get();
  public final static int IGTL_TYPE_USE_LONG_LONG = IGTLutilJNI.IGTL_TYPE_USE_LONG_LONG_get();
  public final static int IGTL_SIZEOF_LONG_LONG = IGTLutilJNI.IGTL_SIZEOF_LONG_LONG_get();
  public final static int IGTL_SCALAR_INT8 = IGTLutilJNI.IGTL_SCALAR_INT8_get();
  public final static int IGTL_SCALAR_UINT8 = IGTLutilJNI.IGTL_SCALAR_UINT8_get();
  public final static int IGTL_SCALAR_INT16 = IGTLutilJNI.IGTL_SCALAR_INT16_get();
  public final static int IGTL_SCALAR_UINT16 = IGTLutilJNI.IGTL_SCALAR_UINT16_get();
  public final static int IGTL_SCALAR_INT32 = IGTLutilJNI.IGTL_SCALAR_INT32_get();
  public final static int IGTL_SCALAR_UINT32 = IGTLutilJNI.IGTL_SCALAR_UINT32_get();
  public final static int IGTL_SCALAR_FLOAT32 = IGTLutilJNI.IGTL_SCALAR_FLOAT32_get();
  public final static int IGTL_SCALAR_FLOAT64 = IGTLutilJNI.IGTL_SCALAR_FLOAT64_get();
  public final static int IGTL_SCALAR_COMPLEX = IGTLutilJNI.IGTL_SCALAR_COMPLEX_get();
}
