/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package OpenIGTLink.swig;

public interface IGTLpointConstants {
  public final static int IGTL_SIZEOF_CHAR = IGTLpointJNI.IGTL_SIZEOF_CHAR_get();
  public final static int IGTL_SIZEOF_INT = IGTLpointJNI.IGTL_SIZEOF_INT_get();
  public final static int IGTL_SIZEOF_SHORT = IGTLpointJNI.IGTL_SIZEOF_SHORT_get();
  public final static int IGTL_SIZEOF_LONG = IGTLpointJNI.IGTL_SIZEOF_LONG_get();
  public final static int IGTL_SIZEOF_FLOAT = IGTLpointJNI.IGTL_SIZEOF_FLOAT_get();
  public final static int IGTL_SIZEOF_DOUBLE = IGTLpointJNI.IGTL_SIZEOF_DOUBLE_get();
  public final static int IGTL_TYPE_USE_LONG_LONG = IGTLpointJNI.IGTL_TYPE_USE_LONG_LONG_get();
  public final static int IGTL_SIZEOF_LONG_LONG = IGTLpointJNI.IGTL_SIZEOF_LONG_LONG_get();
  public final static int IGTL_POINT_ELEMENT_SIZE = IGTLpointJNI.IGTL_POINT_ELEMENT_SIZE_get();
  public final static int IGTL_POINT_LEN_NAME = IGTLpointJNI.IGTL_POINT_LEN_NAME_get();
  public final static int IGTL_POINT_LEN_GROUP_NAME = IGTLpointJNI.IGTL_POINT_LEN_GROUP_NAME_get();
  public final static int IGTL_POINT_LEN_OWNER = IGTLpointJNI.IGTL_POINT_LEN_OWNER_get();
}
