/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package OpenIGTLink.swig;

public class igtl_ndarray_info {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected igtl_ndarray_info(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(igtl_ndarray_info obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IGTLndarrayJNI.delete_igtl_ndarray_info(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(short value) {
    IGTLndarrayJNI.igtl_ndarray_info_type_set(swigCPtr, this, value);
  }

  public short getType() {
    return IGTLndarrayJNI.igtl_ndarray_info_type_get(swigCPtr, this);
  }

  public void setDim(short value) {
    IGTLndarrayJNI.igtl_ndarray_info_dim_set(swigCPtr, this, value);
  }

  public short getDim() {
    return IGTLndarrayJNI.igtl_ndarray_info_dim_get(swigCPtr, this);
  }

  public void setSize(SWIGTYPE_p_unsigned_short value) {
    IGTLndarrayJNI.igtl_ndarray_info_size_set(swigCPtr, this, SWIGTYPE_p_unsigned_short.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_short getSize() {
    long cPtr = IGTLndarrayJNI.igtl_ndarray_info_size_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
  }

  public void setArray(SWIGTYPE_p_void value) {
    IGTLndarrayJNI.igtl_ndarray_info_array_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getArray() {
    long cPtr = IGTLndarrayJNI.igtl_ndarray_info_array_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public igtl_ndarray_info() {
    this(IGTLndarrayJNI.new_igtl_ndarray_info(), true);
  }

}
