/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package OpenIGTLink.swig;

public class igtl_header {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected igtl_header(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(igtl_header obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IGTLheaderJNI.delete_igtl_header(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVersion(int value) {
    IGTLheaderJNI.igtl_header_version_set(swigCPtr, this, value);
  }

  public int getVersion() {
    return IGTLheaderJNI.igtl_header_version_get(swigCPtr, this);
  }

  public void setName(String value) {
    IGTLheaderJNI.igtl_header_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return IGTLheaderJNI.igtl_header_name_get(swigCPtr, this);
  }

  public void setDevice_name(String value) {
    IGTLheaderJNI.igtl_header_device_name_set(swigCPtr, this, value);
  }

  public String getDevice_name() {
    return IGTLheaderJNI.igtl_header_device_name_get(swigCPtr, this);
  }

  public void setTimestamp(java.math.BigInteger value) {
    IGTLheaderJNI.igtl_header_timestamp_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getTimestamp() {
    return IGTLheaderJNI.igtl_header_timestamp_get(swigCPtr, this);
  }

  public void setBody_size(java.math.BigInteger value) {
    IGTLheaderJNI.igtl_header_body_size_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getBody_size() {
    return IGTLheaderJNI.igtl_header_body_size_get(swigCPtr, this);
  }

  public void setCrc(java.math.BigInteger value) {
    IGTLheaderJNI.igtl_header_crc_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getCrc() {
    return IGTLheaderJNI.igtl_header_crc_get(swigCPtr, this);
  }

  public igtl_header() {
    this(IGTLheaderJNI.new_igtl_header(), true);
  }

}
