/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package OpenIGTLink.swig;

public interface IGTLtransformConstants {
  public final static int IGTL_SIZEOF_CHAR = IGTLtransformJNI.IGTL_SIZEOF_CHAR_get();
  public final static int IGTL_SIZEOF_INT = IGTLtransformJNI.IGTL_SIZEOF_INT_get();
  public final static int IGTL_SIZEOF_SHORT = IGTLtransformJNI.IGTL_SIZEOF_SHORT_get();
  public final static int IGTL_SIZEOF_LONG = IGTLtransformJNI.IGTL_SIZEOF_LONG_get();
  public final static int IGTL_SIZEOF_FLOAT = IGTLtransformJNI.IGTL_SIZEOF_FLOAT_get();
  public final static int IGTL_SIZEOF_DOUBLE = IGTLtransformJNI.IGTL_SIZEOF_DOUBLE_get();
  public final static int IGTL_TYPE_USE_LONG_LONG = IGTLtransformJNI.IGTL_TYPE_USE_LONG_LONG_get();
  public final static int IGTL_SIZEOF_LONG_LONG = IGTLtransformJNI.IGTL_SIZEOF_LONG_LONG_get();
  public final static int IGTL_TRANSFORM_SIZE = IGTLtransformJNI.IGTL_TRANSFORM_SIZE_get();
}
