/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package OpenIGTLink.swig;

public interface IGTtypesConstants {
  public final static int IGTL_SIZEOF_CHAR = IGTtypesJNI.IGTL_SIZEOF_CHAR_get();
  public final static int IGTL_SIZEOF_INT = IGTtypesJNI.IGTL_SIZEOF_INT_get();
  public final static int IGTL_SIZEOF_SHORT = IGTtypesJNI.IGTL_SIZEOF_SHORT_get();
  public final static int IGTL_SIZEOF_LONG = IGTtypesJNI.IGTL_SIZEOF_LONG_get();
  public final static int IGTL_SIZEOF_FLOAT = IGTtypesJNI.IGTL_SIZEOF_FLOAT_get();
  public final static int IGTL_SIZEOF_DOUBLE = IGTtypesJNI.IGTL_SIZEOF_DOUBLE_get();
  public final static int IGTL_TYPE_USE_LONG_LONG = IGTtypesJNI.IGTL_TYPE_USE_LONG_LONG_get();
  public final static int IGTL_SIZEOF_LONG_LONG = IGTtypesJNI.IGTL_SIZEOF_LONG_LONG_get();
}
