/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package OpenIGTLink.swig;

public class SWIGTYPE_p_igtl_uint32 {
  private long swigCPtr;

  protected SWIGTYPE_p_igtl_uint32(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_igtl_uint32() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_igtl_uint32 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

